#!/bin/bash
# Deploy to Render - Quick Start Script

echo "=== Render Deployment Quick Start ==="
echo ""
echo "Before running this script:"
echo "1. Ensure all changes are committed and pushed to GitHub"
echo "2. Create a Render account at https://render.com"
echo "3. Have your database credentials ready"
echo "4. Have your Redis credentials ready (if using)"
echo ""
echo "Steps:"
echo "1. Go to https://render.com/dashboard"
echo "2. Click 'New +' → 'Web Service'"
echo "3. Connect your GitHub repository"
echo "4. Select this branch"
echo "5. Set Environment to 'Docker'"
echo "6. Configure these environment variables:"
echo ""
echo "   Critical:"
echo "   - APP_KEY (run: php artisan key:generate --show)"
echo "   - APP_URL (your Render URL)"
echo "   - DB_HOST, DB_PORT, DB_DATABASE, DB_USERNAME, DB_PASSWORD"
echo ""
echo "   For Cache/Queue:"
echo "   - REDIS_HOST, REDIS_PORT, REDIS_PASSWORD"
echo ""
echo "   For File Storage:"
echo "   - AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY"
echo "   - AWS_DEFAULT_REGION, AWS_BUCKET"
echo "   - FILESYSTEM_DRIVER=s3"
echo ""
echo "7. Click 'Create Web Service'"
echo ""
echo "Documentation:"
echo "- Full guide: RENDER_DEPLOYMENT.md"
echo "- Docker setup: DOCKER_SETUP.md"
echo ""
